### ISSUE TITLE
Pythonic Inheritance issue in Shop by brand module.

### ISSUE THREAD

**Issue by ghost** [OCA/e-commerce#105]
Hello Community,

I am facing the issue in importing website_sale class of website_sale module.

The Issue is raised because of the pythonic override of website_sale class.

Here you will find the reference.

https://github.com/OCA/e-commerce/blob/9.0/website_sale_product_brand/controllers/main.py#L59

Can anybody please help me to fix this issue ?

Regards.
#103

**Comment by ghost** [comment]
CCing @pedrobaeza @Yajo Can you please help me out to overcome this situation ?

I am migrating website_sale_recently_viewed_products in v9.

I need to import the class website_sale and because of this pythonic override, I am not able to import the class.

Thanks in advance.

**Comment by pedrobaeza** [comment]
This is not pythonic, it's monkeypatching. You have to remove that and use inheritance.

**Comment by ghost** [comment]
@pedrobaeza Thanks for your prompt response.

Looking for the solution.

:+1:

**Comment by oscarolar** [comment]
Yeah, just remove that line and you are done. (if there is no other monkey patch.)

**Comment by pedrobaeza** [comment]
Closing as done
