### ISSUE TITLE
Transifex creates i18n folder for non-existing module in 8.0 branch

### ISSUE THREAD

**Issue by atchuthan** [OCA/e-commerce#114]
OCA Transbot created i18n folder for product_multi_link module which is available for 9.0 version only.
https://github.com/OCA/e-commerce/tree/8.0/product_multi_link/i18n
This issue seems very weird to me.

**Comment by pedrobaeza** [comment]
This is because in some moment in time, this module belongs to this repository, and the resource in Transifex was created. Check this issue with the explanation: https://github.com/OCA/maintainer-quality-tools/issues/265
