### ISSUE TITLE
RFC: Qty Options by Pricelist in Website Sale

### ISSUE THREAD

**Issue by lasley** [OCA/e-commerce#121]
I can't figure out a way to do this, so new module in planning. Please let me know if I'm missing something stupid because this really seems like it should exist, or if you have any additional thoughts 😄 

By creating a pricelist that has multiple of the same product on it just with different a `min qty` option, you are able to create pricing tiers to incentivize bulk purchases.

The pricing itself works great if you use the `qty` field during the website shopping process, but the customer has to know that these pricing tiers exist.

My proposal is to handle pricelist tiers similar to variants, providing a radio selection with the min qty and the price for that qty. 

The radios themselves would only need to have some JS that would manipulate the existing qty field, triggering the existing pricing handler.

cc @laslabs

**Comment by pedrobaeza** [comment]
There's nothing about this across OCA. The rationale and implementation details seems OK to me. 

Something similar were done here for supplier prices: https://github.com/OCA/product-attribute/tree/8.0/product_supplierinfo_tree_price_info

**Comment by jjscarafia** [comment]
Hi Dave.
We have developed this module
https://github.com/ingadhoc/product/tree/8.0/product_uom_prices that allows
you to define different prices per UoM used.
We haven't propose it to OCA because I'm still not sure about this aproach.
(we use a new field "computed price list" that can be extended with margin,
price by uom or price by currency).
We have plans to integrate it for ecommerce as you suggest (would be new
module "website_producto_uom_prices").
I would like to cooperate in any possible way.
Thans,
Juan

**Comment by lasley** [comment]
Thanks for the links guys!

@jjscarafia Using your module, what is the strategy if the pricing tiers are at 1, 30, and 60 units & someone wants 35 units?

**Comment by jjscarafia** [comment]
@lasley He need to chose the unit, so, if he want 35 he can order 1 of 30 and 5 of 1 unit. Or, of course, 35 of 1 unit (but no discount there...)

**Comment by lasley** [comment]
Thanks for the elaboration @jjscarafia - I had a feeling that was going to be the case. This is unfortunately a no-go for my requirements, because it will create ambiguity in the ordering process & not allow customers to obtain the discount on all units.

I'm thinking this `_compute_unit_price` method in `product_supplierinfo_tree_price_info` is the key to the woes here, just with some slightly altered logic. Then it's just a matter of displaying some radios and a little JS to update the quantities on click.

**Comment by lasley** [comment]
Closing to track in PR #131
