### ISSUE TITLE
translation extraction in website_sale_require_login

### ISSUE THREAD

**Issue by bealdav** [OCA/e-commerce#161]
## What's wrong
I don't know how to prevent odoo to extract string which shouldn't be translated

https://github.com/OCA/e-commerce/blob/8.0/website_sale_require_login/views/website_sale.xml#L15-L20

Don't you think it could have side effect if we translate ?
https://github.com/OCA/e-commerce/blob/8.0/website_sale_require_login/i18n/it.po#L23-L30

Thanks dear experts @Yajo @pedrobaeza

**Comment by pedrobaeza** [comment]
Yeah, that can be a potential problem. Use `translation="off"` in the label for solving it: https://www.odoo.com/documentation/8.0/reference/translations.html

**Comment by yajo** [comment]
You have a typo, it's `t-translation="off"`.

BTW, this [should not affect v9+](https://github.com/odoo/odoo/blob/9.0/openerp/tools/translate.py#L236).

**Comment by bealdav** [comment]
TIL another tips

https://github.com/OCA/e-commerce/pull/162

Thanks
