### ISSUE TITLE
[Question][7.0] Why is payment automation not available?

### ISSUE THREAD

**Issue by atchuthan** [OCA/e-commerce#19]
I am using Prestashop-connector to import sales order with rule as PAID.  With the help of automatic_workflow module, invoice is validated for the corresponding Sales order but the payment is NOT PAID.

So, why is this process not DONE? Is there any special case.

For now, I have tried to use "sale_quick_payment" module and used the pay_sale_order(..) method to create the payment at Sales order.  But I need to know whether I can do this?

**Comment by guewen** [comment]
Hi,

can report your issue on the https://github.com/OCA/connector-prestashop project please?

Thanks
