### ISSUE TITLE
[wish][10.0] website_sale_wishlist : customise wishlist view separately

### ISSUE THREAD

**Issue by zeroheure** [OCA/e-commerce#201]
Curently, the module use products view to display the wishlist. It is simple and works well. But every layout feature activated (with customize menu) on the products view comes also in the wishlist view (like cart button, stock amount, etc.).
Don't know if it is possible, but it would useful to customize the wishlist separatly from the product list view.

Use case
- display products in combo view with picture and price only
- display wishlist in list view with picture, price, product description, add to cart button and remove from wish button

**Comment by pedrobaeza** [comment]
No, that was a design decision to keep the same view. The same arguments can be said against doing a separate view (you lose all the the customizations made to  the other view).

**Comment by zeroheure** [comment]
I know, I've read the comments in the PR from Yajo. But, can't it still use the same view and be customized separately ?

**Comment by pedrobaeza** [comment]
Not with current architecture. If you want to do it and propose a PR...
