### ISSUE TITLE
website_sale_category_megamenu: 4th, 5th, ... level does not work

### ISSUE THREAD

**Issue by osadmn** [OCA/e-commerce#206]
Dived into the code to look for a solution and I think changing the `$('div > li > ul > li.has-children')` to `$('ul > li.has-children')` line in the frontend.js file might be part of the solution. But then there's still a css issue ... the li elements are horizontally placed instead of vertically so that elements overlap when descending the hierarchy.

**Comment by pedrobaeza** [comment]
This menu is not intended for that number of levels.

**Comment by osadmn** [comment]
But it works for as many levels as you want. Found a css fix too. Added `#categories_megamenu li.active > ul > li.active {
    width: 100%;
}` to the megamenu.css file. (Don't know if it's the most elegant solution but it does the trick.)

**Comment by pedrobaeza** [comment]
Please make a PR then.
