### ISSUE TITLE
[9.0][BUG][website_sale_qty] Error 403: Forbidden when trying to buy anything

### ISSUE THREAD

**Issue by rafaelbn** [OCA/e-commerce#216]
Hi @obulkin @lasley,

In v9 with you module `website_sale_qty` we cannot test any module in runbot because in shop if you select a product it gives you an error:

```
403: Forbidden

The page you were looking for could not be authorized.

Maybe you were looking for one of these popular pages ?

    Homepage
    Contact Us
```

When uninstalling you module it works.

Please could you review and update v9 module's version like v10?

Thanks!

**Comment by obulkin** [comment]
Thanks for reporting this issue, @rafaelbn. It actually exists in v10 as well but was masked by the fact that the relevant template is inactive by default in this version.

I've submitted fixes for both: https://github.com/OCA/e-commerce/pull/217 and https://github.com/OCA/e-commerce/pull/218

**Comment by rafaelbn** [comment]
Solved, thanks @obulkin
