### ISSUE TITLE
website_sale_hide_price

### ISSUE THREAD

**Issue by larmar** [OCA/e-commerce#229]
I have been using similar code. But I have also removed the Add to cart button and variants.

You don't want the user to see variant prices, like 16GB/32GB ipod
And you don't want users to "add to cart" and see the price 
I would suggest to enhance this mod with that.

The code sample I use in v11 ( specific for Public user ) Your mode is more general:-)  
```
<t t-if="not user_id._is_public()">
   <t t-call="website_sale.product_price"/>
   <p t-if="len(product.product_variant_ids) &gt; 1" class="css_not_available_msg bg-danger" style="padding:15px;">This combination does not exist.</p>
   <a id="add_to_cart" class="btn btn-primary btn-lg mt8 js_check_product a-submit" href="#">Add to Cart</a>
</t>
```

**Comment by pedrobaeza** [comment]
Please make the proper PR.

**Comment by pedrobaeza** [comment]
Closing as no PR nor answer.
