### ISSUE TITLE
[11.0] website_sale_hide_price show prices on cart for public user

### ISSUE THREAD

**Issue by pedroguirao** [OCA/e-commerce#242]
Hi all, 

The module correctly hide the price on shop page or product page but still you can add to cart the product and view the price on cart. 

Best regards,

**Comment by pedrobaeza** [comment]
That's an extra feature not covered. Normal thing is to disable the add to cart option in these cases.

**Comment by pedrobaeza** [comment]
@AbrahamTrey what do you think about this?

**Comment by pedroguirao** [comment]
Thank you Pedro,

Is this feature avaiable in other module or is a native odoo conf?.

**Comment by pedrobaeza** [comment]
It's a native Odoo feature in customize dropdown.

**Comment by pedroguirao** [comment]
This feature remove the "add to cart" for all user's,  don't suit for our case.

Thank you again for your answer.

**Comment by pedrobaeza** [comment]
Then you should develop the new feature in website_sale_hide_price (and ideally propose it here in OCA) or hire someone for doing it.

**Comment by antoniocanovas** [comment]
I think that "Add to cart" and "Quantity" in product view must be hidden as well as the price, to public user.

Nobody will buy before login if he can't see the prices.

**Comment by JuanjoA** [comment]
+1 @antoniocanovas 
Maybe I can make time to take a look at it.

**Comment by rafaelbn** [comment]
Closing as attended in https://github.com/OCA/e-commerce/pull/244
