### ISSUE TITLE
Hiding Price Removes "Add to Cart" Button

### ISSUE THREAD

**Issue by knorquist** [OCA/e-commerce#291]
Odoo 11, Debian 9, Community Edition.

Toggling "Show prices on website" removes the "Add to Cart" button for customers.

I'd like to be able to remove prices but still allow ordering. Is this user error and I need a different solution?

![image](https://user-images.githubusercontent.com/3306524/58273305-42e48a00-7d45-11e9-91c2-66e4fc769cf6.png)

![image](https://user-images.githubusercontent.com/3306524/58273337-5b54a480-7d45-11e9-9371-71d5cbe8704c.png)

**Comment by chienandalu** [comment]
Hi, @knorquist This module is intended to use the online store in a sort of catalog mode. So the behavior is intended.

As a customer, if you don't know the price of the product your ordering, would you try to buy it anyway?

**Comment by knorquist** [comment]
We're using our store internally, so we didn't want "customers", i.e. our employees seeing a price and thinking they actually owed money. We were considering just setting the dollar value of everything as $1 and letting everyone know they didn't actually owe anything, but simply hiding the prices would be ideal.

We tried setting everything to $0 but that seemed to break things (errors on checkout and stuff), so that wasn't an option.

**Comment by chienandalu** [comment]
Sorry, but in that very specific scenario, this module won't fit your needs.
