### ISSUE TITLE
naming : e-commerce but connector-ecommerce

### ISSUE THREAD

**Issue by zeroheure** [OCA/e-commerce#308]
This repo is named e-commerce with a dash, while connector-ecommerce doesn't have a dash. It doesn't help to find repository, and I find this boring. Can we add both writings in the names (the option is in each repository settings) ?

**Comment by pedrobaeza** [comment]
connector-e-commerce would result very weird... OCA/ecommerce can be an option.

**Comment by shellwang** [comment]
Yes, please see the option before.
