### ISSUE TITLE
unit price not display the pricelist discounts in website_sale_secondary_unit

### ISSUE THREAD

**Issue by eversatis** [OCA/e-commerce#341]
I set discount for 20% off for all product for quantity over 10 in pricelist:
![image](https://user-images.githubusercontent.com/10336015/77252373-73ab8d80-6c8e-11ea-9d9f-cdc284ff2e50.png)

Unit price on product page do not judge the pricelist discounts.
![image](https://user-images.githubusercontent.com/10336015/77252021-b66c6600-6c8c-11ea-960a-20df734423b5.png)
If I switch to uom Dozens or set default sale uom to Dozens, the unit price should display the discounted price similar as the following default one.
![image](https://user-images.githubusercontent.com/10336015/77252322-0bf54280-6c8e-11ea-9c18-b5591b7b2301.png)
On the cart page, the discount do implemented:
![image](https://user-images.githubusercontent.com/10336015/77252334-229b9980-6c8e-11ea-9763-ac8a587d6170.png)

**Comment by pedrobaeza** [comment]
I don't get the exact problem.
