### ISSUE TITLE
Filename destroys repo usability on systems which do not allow colon as part of a filename

### ISSUE THREAD

**Issue by wtaferner** [OCA/e-commerce#379]
@sergio-teruel @pedrobaeza 
Since commit https://github.com/OCA/e-commerce/commit/4d30933778b6acd9ebbbb43a8cb0cc5cf36889ad and adding this [image](https://github.com/OCA/e-commerce/blob/11.0/website_sale_product_detail_attribute_image/static/src/img/EN374:2003.png) it is a nightmare (impossible) to checkout or work with this repo on systems not supporting this kind of filename.

Basically we have to break the commit and merge chain to fix this, right? Any idea how we can avoid to have such culprit in the future?

**Comment by pedrobaeza** [comment]
Although I agree `:` is not the best to be put in the filename, which system are you using without its support? POSIX systems should...

**Comment by wtaferner** [comment]
It depends on the used filesystem, so basically I have this [reference](https://en.wikipedia.org/wiki/Filename#Comparison_of_filename_limitations) for you to check in detail (reserved characters)

exFAT, NTFS, HFS, HFS+ to name the most prominent filesystems

And I guess the editing and checking out of this repo should be supported on any OS with almost any used filesystem :stuck_out_tongue_winking_eye:

**Comment by pedrobaeza** [comment]
Please make a PR changing the filename.

**Comment by wtaferner** [comment]
Not ideal to fix this repo, but rewrite is no option...at least accessibility on the latest commit should be possible (untested).

Who could do the CI check for all OCA repos to avoid future repo incompatibilities?

**Comment by pedrobaeza** [comment]
Write a linter in OCA/pylint-odoo

**Comment by wtaferner** [comment]
@pedrobaeza 
Thx, forked it, not sure if I will find time to actually do it, but thx for the pointer and your help.
