### ISSUE TITLE
[12.0][BUG][website_sale_suggest_create_account] 404: Page not found!

### ISSUE THREAD

**Issue by rafaelbn** [OCA/e-commerce#412]
@Yajo @eLBati please

1. Go to runbot
2. Buy and press "Sign up and checkout"
3. You get a 404: Page not found! Here with this URL

http://3432322-12-0-004e2c.runbot2-3.odoo-community.org/web/signup?redirect=/shop/checkout?express=1

See:

![website_sale_suggest_create_account](https://user-images.githubusercontent.com/8736623/88109323-94d3aa80-cbaa-11ea-9a53-534caa0d324a.gif)

**Comment by yajo** [comment]
Fix in #413.
