### ISSUE TITLE
New module for validate phone from website_sale

### ISSUE THREAD

**Issue by celm1990** [OCA/e-commerce#421]
Hi everyone i search a module for validate phone numbers from website(shop, checkout) and not find nothing, Odoo have a [`phone_validation`](https://github.com/odoo/odoo/tree/12.0/addons/phone_validation) base  module. I review module [`website_crm_phone_validation`](https://github.com/odoo/odoo/tree/12.0/addons/website_crm_phone_validation) and and i need create a module similar: _website_sale_phone_validation_(f.e.) than do you thing over this new module?.

**Comment by mamcode** [comment]
Hi Carlos, I think that is a good idea and it would be a great
contribution. For me +1.

**Comment by celm1990** [comment]
Hi @mamcode please help me review PR #422

**Comment by pedrobaeza** [comment]
Closing as there's  PR about this.
