### ISSUE TITLE
Does it work for Odoo 13?

### ISSUE THREAD

**Issue by realhossam** [OCA/e-commerce#436]
Does it work for Odoo 13?

**Comment by simahawk** [comment]
what?

**Comment by realhossam** [comment]
Actually I am new to odoo, I just tried this hide price module, but I don't know what to do exactly, so maybe after this introduction about myself someone will reply with something useful instead of "what" or nonsense answers.
I am not arrogant, but I don't like arrogant people...

**Comment by pedrobaeza** [comment]
Seriously? Is arrogant to ask about which module? This repository contains hundred of modules. You have deserved a closing for that and also this being an issue tracker, not a question one.

Take arrogance.

**Comment by simahawk** [comment]
@realhossam my question was legit and not arrogant at all. I can't say the same about your answer.

You posted a question without any context, without even a reference to the module you were trying -> this makes your question nonsense.

Now, this could happen. We are humans, not bots. This should not be or start a flame war. Nobody here should take it personal.

Hence, if you have any question, please come back with them (here or in other repos) but make sure you provide context on _what_ your are talking about. :wink: 

Thanks for your understanding and collaboration :pray:

**Comment by pedrobaeza** [comment]
@simahawk remember that this issue tracker is not for questions, and a minimal investigation will lead the user to #304. Why should we reward non contributor laziness?

**Comment by realhossam** [comment]
I won't go that level, enjoy your odoo or whatever rocket science u r into

**Comment by simahawk** [comment]
@pedrobaeza please, try to not so hard with newcomers. Leading to that page will still provide him no info on how to move forward. In any case it's legit to have a question and it's legit to give an answer that guides to what somebody is looking for as long as possible. If you don't have time to follow up, just ignore and wait for someone else to reply. Thanks! :pray:

**Comment by pedrobaeza** [comment]
@simahawk and then we have literally thousand of opened issues that are not issues and not answered nor closed.

**Comment by simahawk** [comment]
@realhossam if you are talking about `website_sale_hide_price` (as I could guess from #439) then the answer for your initial question is "Is not yet ported to v13". As you can see the module is not available in the 13.0 branch https://github.com/OCA/e-commerce/tree/13.0.
