### ISSUE TITLE
Where can I find the public user partner

### ISSUE THREAD

**Issue by realhossam** [OCA/e-commerce#439]
they mentioned the following statement:
"If you wanted to have the prices hidden by default when no user is logged in you should go to Public User's partner and set Show prices on website off."

I can't find this public user partner and I am new to this odoo, so many things I still can't figure it out, so if someone can write down step by step on how to do this

Note: My need is to hide product price from public user

**Comment by pedrobaeza** [comment]
No issue, but question.

**Comment by realhossam** [comment]
> No issue, but question.

So where can I open a question

**Comment by pedrobaeza** [comment]
On Odoo forums.

**Comment by pedrobaeza** [comment]
With complete information, not half, even without mentioning. Module and module URL, Odoo version...

**Comment by realhossam** [comment]
very strange software communities nowadays, that wasn't the case in 2006, as if its like taboo or something to answer my question.

**Comment by HviorForgeFlow** [comment]
![image](https://user-images.githubusercontent.com/32061121/94902533-9c5fdb80-0498-11eb-8e76-36ad43e2f54e.png)

**Comment by zzwxrchi** [comment]
In v14:
Go to "Contacts"
--Filters -> Archived
---Select: "Public user" and click on "Edit"
------Select: "Sales & Purchase"
--------Deselect: "Show prices on website" and "Save"

**Comment by zzwxrchi** [comment]
> very strange software communities nowadays, that wasn't the case in 2006, as if its like taboo or something to answer my question.

Sorry @pedrobaeza ! Pudes no cerrar preguntas tan rapido ?
Por menos espera un par de dias.

Hay gente que le gusta ayudar y mejora la comunidad, como @HviorForgeFlow .

Disculpa por si te he o habia ofendido, pero es lo que pienso de verdad.
No soy tan bueno en conocimiento como tu, pero es mi voz.

**Comment by pedrobaeza** [comment]
This is not the place for questions.

**Comment by zzwxrchi** [comment]
> This is not the place for questions.

Por naturaleza, este es mejor sitio para preguntar algo. No entiendo porque mandar preguntas a un sitio mas lejos.

Creo que Odoo forums no es buen sitio para preguntas de extra addons. 
Encima, estamal organizado, tiene muy poca informacion, si pongo buscar "find the public user partner", me responde "Sorry, we could not find any result matching..."

Las dudas sobre un modulo concreto, es mas eficaz ir directamente aquí. Puede ver sus disarolladors, otros usarios a la vez y no mezcla con otras preguntas sobre otras parte odoo o otras addons.
