### ISSUE TITLE
[13.0] website_sale_product_detail_attribute_image: Forward-port PR #381

### ISSUE THREAD

**Issue by JulienCochuyt** [OCA/e-commerce#469]
As described in #379, filenames containing a colon practically cannot be checked out under Windows.
Commit 4d30933 introduced such a file, namely: `website_sale_product_detail_attribute_image/static/src/img/EN374:2003.png`
This was fixed for branch `11.0` by PR #383 
Could you please consider porting this fix to other branches so that the `e-commerce` repo can again be checked out under Windows?
My main interest is towards `13.0`, but I guess `12.0` and `14.0` should ideally be impacted as well..

**Comment by pedrobaeza** [comment]
Or you can do it yourself cherry-picking such commit and proposing the corresponding PR. Anyway, an advice: avoid Windows, as this is only one of the infinite troubles you will find in this ecosystem.
