### ISSUE TITLE
Move sale_automatic_workflow and sale_payment_method to sale-workflow project

### ISSUE THREAD

**Issue by bguillot** [OCA/e-commerce#47]
Hello, 

I am here to discuss about moving the modules sale_automatic_workflow (and derived) and sale_payment_method (and derived) to the project sale-workflow. 

First of all those modules are very linked with other sale-workflow modules, it leads to loop dependencies for travis for instance (modules in e-commerce depends on modules in sale-workflow). 
That's why @gurneyalex and @sebastienbeau suggested to move at least sale_payment_method in my PR https://github.com/OCA/sale-workflow/pull/121

Moreover, thoses modules can be used even in a non e-commerce company (you may want to automate the validation of sale_orders or invoices without having an e-commerce shop).

So after discussing with @guewen it appears that maybe sale_automatic_workflow, sale_payment_method and sale_payment_method_automatic_workflow would be better in sale-workflow project (product_links is still relevant in e-commerce).

That makes also sense for the unpported modules : sale_quick_payment, sale_automatic_workflow_exceptions and sale_payment_method_transaction_id (thoses are glues modules).

Before extracting the branches I would like to have your opinions about that and what will be the best procedure to do it (indeed thoses modules are concerned by some PR's).

I can first do it with sale_payment_method (no PR in 7 or 8).

Thanks for your feedbacks

**Comment by gurneyalex** [comment]
I'm :+1: on this in principle, but let's not rush things. I'll raise attention on the contributors mailing list.

**Comment by max3903** [comment]
:+1:

**Comment by florian-dacosta** [comment]
:+1:

**Comment by bealdav** [comment]
:+1:

**Comment by petrus-v** [comment]
:+1: 

I wonder if it's possible to let somehow a message to let users know where to find the new repo host

**Comment by pedrobaeza** [comment]
I also think that e-commerce repository overlaps a lot of others repositories, and more over, e-commerce is only one channel more, not an isolated flow itself, so I prefer to remove this repo and split its contents in the corresponding areas repos.

**Comment by nbessi** [comment]
I'm :+1:  on the concept but I do not want to break any existing setup. One of the role of OCA is to provide some stability. We were angry enought with Odoo coboy release let's try to do better.

**Comment by jgrandguillaume** [comment]
:+1:  to move it

**Comment by leio** [comment]
Sounds good as I use them outside of e-commerce connectors too (for sort of a prepayment workflow), but please handle some of the mentioned unported modules too then, and any of their issues or PRs as good as github allows (I have ongoing PR for porting one of them)

**Comment by guewen** [comment]
I discussed about that with @bguillot and agree. The modules are not only related to e-commerce and overlap with other repositories, mainly sale-workflow. :+1:

**Comment by OSguard** [comment]
I agree also to remove this repository and move it outside. :+1:

**Comment by houssine78** [comment]
:+1:

**Comment by bguillot** [comment]
Thanks for your answers, 

It seems that everyone agree with that. 

@nbessi I think most of people that use e-commerce modules will also use sale-workflow so it should not be too dangerous for existing deployments.

I will make a PR to move sale_payment_method (because it has no current PR). But what is the process to move the PR's from e-commerce to sale-workflow ?

**Comment by nbessi** [comment]
@bguillot ok but at least we should have a mail on community mailing list before/when proceeding

**Comment by LeartS** [comment]
What's the status of this? Now that Odoo has its own e-commerce module I think it's important to "clean" this.

**Comment by pedrobaeza** [comment]
I can merge as this has enough thumbs up.

**Comment by pedrobaeza** [comment]
But I don't see PR for the move in sale-workflow. Can you do it?

**Comment by LeartS** [comment]
@pedrobaeza who are you talking to?

**Comment by pedrobaeza** [comment]
Well, actually it can be anyone, but I refer to one of the involved in this conversation.

**Comment by bguillot** [comment]
Hello,

I started to make PRs here : 

https://github.com/OCA/sale-workflow/pull/172

https://github.com/OCA/sale-workflow/pull/171

**Comment by gurneyalex** [comment]
I'm thinking we should probably add a ChangeLog file at the root of the project for modules which get moved from one project to another. At least this will give the people a hint about where to look.

**Comment by rafaelbn** [comment]
:+1: for moving

**Comment by lepistone** [comment]
So here is a checklist:
- `sale_quick_payment`
  - 8.0 OCA/sale-workflow#239 OCA/e-commerce#86
- `sale_payment_method`
  - 7.0 OCA/sale-workflow#171
  - ~~8.0 OCA/sale-workflow#172~~ ~~#88~~ **merged!**
- `sale_automatic_workflow`, `sale_payment_method_automatic_workflow` `sale_automatic_workflow_exception` `sale_payment_method_transaction_id` OCA/sale-workflow#240 OCA/e-commerce#87

And all the open pull requests that involve those modules. I am migrating:
- #54 
- #55
- #80

**Comment by antespi** [comment]
This PR is also needed too https://github.com/OCA/e-commerce/pull/88, because https://github.com/OCA/sale-workflow/pull/172 is already merged

**Comment by lepistone** [comment]
Thanks @antespi, I updated the list above.

**Comment by pedrobaeza** [comment]
This has been done, so I close.
