### ISSUE TITLE
[12.0] website_sale_attribute_filter_price causes context overwriting

### ISSUE THREAD

**Issue by dalonsod** [OCA/e-commerce#476]
Hello,

using other addon (`website_sale_product_brand`) I've experienced the following issue: clicking on a certain brand from the frontend (`/page/product_brands`) redirects to the shop, but the brand filter is not applied.

Debugging the the code I've found that brand value is registered in the `request.env.context` (https://github.com/OCA/e-commerce/blob/12.0/website_sale_product_brand/controllers/main.py#L31), but when it's intended to be used for the domain search construction (https://github.com/OCA/e-commerce/blob/12.0/website_sale_product_brand/controllers/main.py#L14) `request.env.context` has already lost this data.

Looking for other addons that could cause this issue, I've uninstalled `website_sale_attribute_filter_price`, which I was using too, and the issue is gone. When executing step-by-step, after this line (https://github.com/OCA/e-commerce/blob/12.0/website_sale_attribute_filter_price/controllers/website_sale.py#L45) `brand_id` context value is lost. I'm newbie in e-commerce app but, are `request.context` references correct, or should be `request.env.context` used instead?

Tried to test on v12 OCA e-commerce runbot, but `admin` password for `admin` user didn't work for me today.

cc @Tardo @chienandalu

**Comment by dalonsod** [comment]
Update: tested on v13 runbot, selecting "Apple" brand every product is listed, when only two of them have that brand. So, the bug is also present.

v12 runbot database credentials `admin / admin` still don't work. @OCA/e-commerce-maintainers could you check, is there any problem with it? Maybe the instance should be re-created

**Comment by Tardo** [comment]
Thanks for report it!
