### ISSUE TITLE
[12.0] Error with cart popover when using website_sale_secondary_unit 

### ISSUE THREAD

**Issue by nmoturi** [OCA/e-commerce#477]
Hi Team,

Did anyone faced an issue with cart popover when website_sale_secondary_unit..?

Thanks,
Naran

ValueError: Element xpath expr="//div[hasclass('col-9')]" cannot be located in parent view

Error context:
View `cart_popover`
[view_id: 2526, xml_id: website_sale_secondary_unit.cart_popover, model: n/a, parent_id: 1008]

load could not load template
Template: 1008

**Comment by pedrobaeza** [comment]
Steps to reproduce the problem on OCA runbot?
