### ISSUE TITLE
 How to use the client fiscal position in the POS ? 

### ISSUE THREAD

**Issue by usinepi** [OCA/e-commerce#482]
Hello ! 
I'm trying to use the fiscal position of my client in the POS (community V9).
According to my tests, the specific fiscal position is taken into account on Sales orders but not on Point of sale orders. The only thing I found is to change the fiscal position for all the orders being made in the POS but not according to the client (or to select it manually if you set up several fiscal positions in the POS settings). Is there a way to do so ?

The main goal is to be able to "sell" products with 100% discount (products we haven't sold and need to give/throw away). To avoid making the discount on each products, we've set up the "discount on the all ticket" option but we've noticed that if you do so, the discount is not applied on the taxes (only if you make a discount per product). This is a problem for us cause it makes us pay taxes for unsold products.
That's why we've decided to create a special client for the product we're throwing away and we want to apply a fiscal position for this client that would be taxes = 0% to skirt the problem.
If you have other ideas... welcome !

Thanks in advance

**Comment by pedrobaeza** [comment]
Unrelated question to this repo. Please use Odoo forums for that.
