### ISSUE TITLE
[13.0] website_sale_product_detail_attribute

### ISSUE THREAD

**Issue by teds-it** [OCA/e-commerce#500]
Hi All,

Is it possible to hide the image which is assigned to an attribute and show the image only when the product variant is selected?
Now all assigned images are showning... I would like to see the picture only when a variant is selected...
Please see the attached image for more info..

Thanks in advance!
![2021-02-17 15_39_59-Detailing pakketten _ NCT](https://user-images.githubusercontent.com/58508189/108220271-d7f0fe80-7136-11eb-8996-0ca0c960c970.png)

**Comment by teds-it** [comment]
wow, nobody has a clue?

**Comment by rogie69** [comment]
Hi,
This sound like a good idea, I am after the same thing
