### ISSUE TITLE
Feature Enhancements & Question

### ISSUE THREAD

**Issue by walkerblackwell** [OCA/e-commerce#510]
In some future version of Odoo it would be nice to have the following:

1. Stock availability for all products on both Shop List and Product pages (stocked and variant and kit/consumable).
2. ajax add-to-cart from product page by default.
3. Ability to auto-relate 1 or more attributes for a given product on a product page and show related attributes linked to those specific products. --> This would get rid of the need for product variants entirely. Product variants are a problem in Odoo for real ecommerce businesses for so so many reasons . . .
4. Horizontal attribute filters on shop list pages as option (and do this with searchable filter list).

All of these things I have implemented at shop (dot) inkjetmall (dot) com but would like to maybe offer to contribute to some future FOSS coding work. It's very tightly bound to our theme though so extricating all of this code could take some time . . . my question would be what is the best way to go about contributing, and does anyone else here want to collaborate on these features?

best,
Walker

**Comment by chienandalu** [comment]
> my question would be what is the best way to go about contributing, and does anyone else here want to collaborate on these features?

Hi @walkerblackwell  These videos from OCA Community can be a good starting point:

- https://www.youtube.com/watch?v=mMTc2_Qn8Mw
- https://www.youtube.com/watch?v=tJZptwfjv2I
- https://www.youtube.com/watch?v=41Yzp1fBiKk
