### ISSUE TITLE
Incompatible CSRF control between Odoo 14 and website_sale_suggest_create_account addon

### ISSUE THREAD

**Issue by Smartstores2021** [OCA/e-commerce#541]
module: website_sale_suggest_create_account and Odoo e-commerce V14
version: 14.0

**Steps to reproduce**
- Login with user acoount A and at the same time add to cart in other computer with user account B or not loged in user.
- This effect was maked in simulated scenario using  uipath RPA for create concurrent events.

**Current behavior**
- Unexpected and random mixing user sessions when many customers navigate in the e-commerce at the same time.
- My team work inspect the problem and find that Odoo use CSRF token as standard for security reassons but the addon disable this and the consistency is unexpected.

**Expected behavior**
- The website_sale_suggest_create_account addon was installed for increase the securty forcing to create account previous to proced with sales and checkout, as second benefit we are collecting with consent the contact information of buyers for marketing campaigns.

**Comment by pedrobaeza** [comment]
The module you mention is not migrated yet to v14, so it's normal that it doesn't behave correctly. You should never use a module from another Odoo version.
