### ISSUE TITLE
[13.0][website_sale_stock_available] Unable to select any options in settings

### ISSUE THREAD

**Issue by ghost** [OCA/e-commerce#544]
We installed the module yesterday and it has added the available and potential values have been added to products

However in the Inventory > Configuration > Settings, if we select either of the tick-boxes in the _available to promise_ section, the settings do not save. We click save and they are unticked again.

Is this a bug or user error. Are there logs we can look at for debugging?

Thanks

**Comment by pedrobaeza** [comment]
That options has nothing to do with this module, and they won't probably work because they are modules to be installed that are not available in your system (or not yet migrated). You haven't even indicated the Odoo version.

**Comment by ghost** [comment]
Thanks for your response, although I do find it confusing.
I was following in the readme for the website_sale_stock_available module we installed (with its dependencies).
It states:
> Go to Inventory > Configuration > Settings, navigate to Stock available to promise section and set the desired option. If you do not choose any, the value of 'Available' quantity will be equal to 'Forecasted' quantity.

I now realise that this may be an issue with the stock_available module so I will open an issue there as well. 

I put the odoo version in the title but if you would like me to be more specific: Odoo 13.0-20200629 (Community Edition) 

As normal, its a pleasure receiving support from you pedro!

**Comment by pedrobaeza** [comment]
Let's close this one then and continue talking on the other one.
