### ISSUE TITLE
website_sale_checkout_skip_payment change force_quotation_send use to _send_order_confirmation_mail

### ISSUE THREAD

**Issue by eabquina** [OCA/e-commerce#562]
**Problem:** 

Odoo v13, after checkout or confirmation step of the shopping cart, an error is encountered saying **force_quotation_send** is missing from sale.order

In this Pull Request. force_quotation_send was already removed and seems to b replaced with _send_order_confirmation_mail
https://github.com/odoo/odoo/pull/28781/files

**Proposed Solution**

Update the module to use the proper method to execute mail send.

**Comment by pedrobaeza** [comment]
I suppose you want to say that this module is incorrect, but in which Odoo version? Can you make the PR doing the needed changes?

**Comment by eabquina** [comment]
Did a sample locally, using the said method works, but the transaction fails at the end at the User, maybe a different method or an extra step needs to be added to the section.

**Comment by pedrobaeza** [comment]
So it seems you are talking about migrating the module. This is not an issue, but a task to be done. Closing then.

**Comment by eabquina** [comment]
No this is not about migrating the module. Just code update. 

But anyways,  it turns out this was already updated. In my case, pulling the 13.0 branch had some issues and somehow did not update this specific module (Git issues probably). It works fine now.

https://github.com/OCA/e-commerce/blob/13.0/website_sale_checkout_skip_payment/controllers/main.py#L25-L42

Closing this and just writing this in here for reference
