### ISSUE TITLE
website_sale_category_megamenu:  missing CSS

### ISSUE THREAD

**Issue by oscarolar** [OCA/e-commerce#59]
![IMAGE](https://www.evernote.com/l/AFydRX5SaZtKIpjHHi36OR5FME6qz-H9BFIB/image.png)

![dunno](https://www.evernote.com/l/AFwIxvM4NQdFapsoIFckUHzyzJ3yyelzQqoB/image.png)

I was trying to undertand what does this app do, please put some screenshots on the module description.

**Comment by pedrobaeza** [comment]
Please check it again, because I have just tried on runbot and it's working fine.

**Comment by oscarolar** [comment]
I tried the "Try Me on Runbot button" and still erroring, Where did you tested it?

**Comment by pedrobaeza** [comment]
Well, I'm trying in the same as well. Maybe you have an outdated link. Try directly on https://runbot.odoo-community.org/
