### ISSUE TITLE
new website snippet "PAY NOW"

### ISSUE THREAD

**Issue by ygol** [OCA/e-commerce#592]
**Is your feature request related to a problem?**
For some use case a user is willing to present a simple website page and add a button "Pay Now" or "Subscribe Now". In this case it is preferable to ease and simplify as much as possible the payment process. 

**Describe the solution you'd like**
Have a website snippet. with a button "PAY NOW" (that can be added (inner content) in another block)
On click by the customer:
- a sale order is created
- a cart is created with the product already added and linked to the SO.
- the customer is redirected to "/shop/payment" to complete the payment

In snippet's configuration:
- select the product.
- Option to select accepted payment means. (give the possibility to force a specific payment mean)

**Describe alternatives you've considered**
- Use odoo's "dynamic products" snippets with added "pay now" community module + maybe hide the "add to cart" button with OCA's "website_sale_cart_selectable" ?!

**Additional context**
Create cart and add products from API
https://www.odoo.com/forum/help-1/create-cart-and-add-products-from-api-169313

Programmatically add products to a cart – Odoo 13
https://stackoverflow.com/questions/63034005/programmatically-add-products-to-a-cart-odoo-13

**Comment by chienandalu** [comment]
Do you know the "Buy now" option? It adds the product to the cart and goes directly to the payment page:

![image](https://user-images.githubusercontent.com/5040182/143028547-3d5580e1-4fad-46c2-997e-3b19c95ab980.png)
