### ISSUE TITLE
website_sale_category_megamenu: Breadcrumb incomplete

### ISSUE THREAD

**Issue by oscarolar** [OCA/e-commerce#60]
I was navigating categories on the e-commerce and noticed that the breadcrumb added by this module does not make a consistent full path of the category, in the image on the example you see "Computers / Case", but the right value for it is "Computers / Components / Case" 
![image](https://www.evernote.com/l/AFyf6TiHsA5HW5sKXK7MrU2OGmnA9f9r2ZUB/image.png)

**Comment by pedrobaeza** [comment]
@Yajo, can you please check this one?

**Comment by yajo** [comment]
Fixed in https://github.com/OCA/e-commerce/pull/83.

**Comment by pedrobaeza** [comment]
This was merged, so I close.
