### ISSUE TITLE
website_sale_category_megamenu: Feature not posible to disable without uninstalling

### ISSUE THREAD

**Issue by oscarolar** [OCA/e-commerce#61]
I was reviewing the code, and cant find the `customize_show="True"` and `active="False"` attrs on the main templates, this two attrs are very useful becacuse we can enable or disable features in the website with no need of uninstall the app itself, can you please add this?, if this is done the feature will be selectable on the customize menu.

Here an example : https://github.com/odoo/odoo/blob/8.0/addons/website_sale/views/templates.xml#L261

**Comment by pedrobaeza** [comment]
Well, although useful, if you install the module, you mean that you want to use it, so for me it's not a needed feature. In v9 with multi-website support, it has more sense because you may want to have in one site but not on another.

If you still see it useful, please make the corresponding PR adding this feature.

**Comment by rafaelbn** [comment]
cc @Yajo

**Comment by yajo** [comment]
@oscarolar Why would you want the module installed to add a disabled feature?

**Comment by oscarolar** [comment]
@Yajo Sorry for the late reply, I was on vacation, well, is good to have the option to disable it at any time you want without uninstalling the module, as @pedrobaeza  said, if you install the module is because you need the feature, in that case I propose `customize_show="True" active="True"` with this approach you will have the option available.

**Comment by yajo** [comment]
Yes, multiwebsite can be a real use case. Please feel free to send us the patch.

**Comment by pedrobaeza** [comment]
@oscarolar, are you going to work on this?

**Comment by oscarolar** [comment]
@pedrobaeza there you go https://github.com/OCA/e-commerce/pull/135

**Comment by pedrobaeza** [comment]
Thanks, closing as it's merged.
