### ISSUE TITLE
Cancel sale order with payment

### ISSUE THREAD

**Issue by bguillot** [OCA/e-commerce#62]
Hi,

I have noticed that in v 8.0 of the module sale_payment_method, there is a raise if you try to cancel a sale order with payments.

The problem is sometimes you want to cancel a sale order but you already received the payment so you want to keep the payment and maybe its better to keep the link between the sale order and the payment.

Should we remove the check in the cancel method or do something else ?

Thank you for you replies

**Comment by pedrobaeza** [comment]
This doesn't apply anymore here, so I close.
