### ISSUE TITLE
[14.0] website_sale_hide_price "Recently Viewed Products" always shows price

### ISSUE THREAD

**Issue by Bilbonet** [OCA/e-commerce#633]
## Module
website_sale_hide_price

## Describe the bug
If you have enabled the option "Recently Viewed Products". In this products always shows the price.

## To Reproduce
**Affected versions**:
14.0

1. Logged in the system with management rights.  In your partner form, uncheck the option "Show prices on website".
2. Go to a product in the web catalog.
3. In the menu custom, activate the option "Recently Viewed Products"
4. When you go to other products you'll see at the bottom the other products you've visited with the prices

**Expected behavior**
The prices shouldn't be shown

**Comment by sergioeix** [comment]
Other versions are affected too. I can confirm it on 13.0

**Comment by pedrobaeza** [comment]
Why don't you look around a bit? #639

**Comment by sergioeix** [comment]
I found this and stop searching, I should had seek a bit more
