### ISSUE TITLE
[8.0] _name = "payment.method"

### ISSUE THREAD

**Issue by Karsten-77** [OCA/e-commerce#64]
In 
/e-commerce/sale_payment_method/payment_method.py

there is missing an     `_inherit = "payment.method"`  in Line 27
without that, the model is rewritten and I got KeyErrors for partner_id, which not exist in that (co)model

Greets
Karsten

**Comment by pedrobaeza** [comment]
From which module? payment.method doesn't exist on Odoo core, so it can't be inherited.

**Comment by Karsten-77** [comment]
https://github.com/odoo/odoo/blob/saas-6/addons/payment/models/payment_acquirer.py

It is the saas-6 8.0

Sorry I have seen that now, but why is there a additional model in payment_acquirer.py?
Do you think it is correct to make it suiteable with that inheritation? I have no errors.

**Comment by pedrobaeza** [comment]
Sorry, but this module is for 8.0, not for saas-6, so it doesn't apply. saas-x Odoo branches are not supported by now on OCA, so you should fork and make your own with the modifications wanted.
