### ISSUE TITLE
website_sale_checkout_country_vat

### ISSUE THREAD

**Issue by kimasplund** [OCA/e-commerce#675]
If OSS is used and i have my shop set to Finland with prices shown with Vat 24% and customer is in Germany with Vat 19% odoo shows the vat0% price + 19% and then the module deducts 24% to show as vat free price.

**Comment by pedrobaeza** [comment]
The problem you mention has nothing to do with the module. Even more, it's more a question of business consulting than a bug, so closing those issue.
