### ISSUE TITLE
Website_sale_hide_price: hidden price message

### ISSUE THREAD

**Issue by JrAdhoc** [OCA/e-commerce#689]
## website_sale_hide_price
The name of the module that has a bug.

## Describe the bug
When a message is set in the field "hidden price message" it displays correctly on a desktop browser, but doesen't show on a mobile device. 

## To Reproduce
**Affected versions**: 13

1. Set hide price on a product
2. Add a hidden price message
3. Compare desktop browser vs mobile device browser

**Expected behavior**
The message should be visible both on desktop and mobile devices

**Additional context**
tested on chrome and safari

**Comment by chienandalu** [comment]
Can you propose a fix?
