### ISSUE TITLE
[website_sale_invoice_address] - display billing address as "billing" in checkout

### ISSUE THREAD

**Issue by francesco-ooops** [OCA/e-commerce#739]
**Is your feature request related to a problem?**

This module changes invoice address in SO for ecommerce orders, as per [description](https://github.com/OCA/e-commerce/tree/15.0/website_sale_invoice_address#usage); however, in checkout user still sees partner's address as billing address. 

This can be confusing as it could lead the customer to believe that their order is being invoiced at the wrong address.

![image](https://user-images.githubusercontent.com/55489873/214904562-a402e800-8f03-4fbb-b409-8cb5792fcd16.png)

**Describe the solution you'd like**
Display the billing address that will be applied in SO to user during checkout.

**Comment by chienandalu** [comment]
Thanks  @francesco-ooops I haven't researched it but my guess is that it comes from a qweb template context. A patch proposal will be welcome as always :smile: :+1:
