### ISSUE TITLE
[website_sale_stock_available] Module depens on "stock_available" but module isn't available in ODOO16

### ISSUE THREAD

**Issue by scrimo** [OCA/e-commerce#782]
Can not install website_sale_stock_available module because there is a depend on "stock_available" module.
stock_available (in repo stock-warehouse-logistics) isn't available in 16.0

This is the same with module pos_stock_available_online module in pos repo

**Comment by pedrobaeza** [comment]
https://github.com/OCA/stock-logistics-availability/tree/16.0/stock_available
