### ISSUE TITLE
[9.0] Moving modules from v8 OCA/e-commerce to v9 OCA/sale-workflow

### ISSUE THREAD

**Issue by rafaelbn** [OCA/e-commerce#81]
Hi,

This discussion has already done here:
- https://github.com/OCA/e-commerce/pull/54
- https://github.com/OCA/e-commerce/issues/47

This issue is to determinate and know specifically which modules in e-commerce are incorrect pushed and we must move to other repo, mainly:  https://github.com/OCA/sale-workflow

In fact there is a **PR about this here**: https://github.com/OCA/sale-workflow/pull/172

AS @bguillot said:
- sale_automatic_workflow
- sale_automatic_workflow_exception
- sale_payment_method
- sale_payment_method_automatic_workflow
- sale_payment_method_transaction_id
- sale_quick_payment

And existing PR:
- https://github.com/OCA/e-commerce/pull/80
- https://github.com/OCA/e-commerce/pull/55
- https://github.com/OCA/e-commerce/pull/54

Thanks

**Comment by pedrobaeza** [comment]
Why don't you write it in the open issue about migration?

**Comment by rafaelbn** [comment]
Closing for make discussion in https://github.com/OCA/e-commerce/issues/63
