### ISSUE TITLE
Price visible in search

### ISSUE THREAD

**Issue by drzaphod85** [OCA/e-commerce#821]
## Module
website_sale_hide_price

## Describe the bug
When the module is installed the when viewing a product or product list the price and "add to cart" are hidden as expected. But if you in the webshop search for a product when the price is visible in the search result. See included picture:
![Capto_Capture 2023-07-12_06-16-47_PM](https://github.com/OCA/e-commerce/assets/39097679/07bc13df-7d47-4f7d-ab0c-4df5333f616d)

## To Reproduce
16.0.1.2.1

1. Install the module in Odoo 16 Enterprise
2. Configure the Public User not to see price
3. Open the website and go to the webshop
4. Search for a product in the webshop search field

**Expected behavior**
The product is displayed as expected without any price

**Additional context**
Odoo version 16 enterprise from the 9th July On-Prem installation on Ubuntu 22.04.

**Comment by liebana** [comment]
@drzaphod85 Can you check and validate https://github.com/OCA/e-commerce/pull/819 ? It fixes your problem.

**Comment by remi-filament** [comment]
Fixed with #819
