### ISSUE TITLE
Error using dynamic content products (block) when using a catergory where all the products are unpublished

### ISSUE THREAD

**Issue by arnaud-tricore** [OCA/e-commerce#834]
## Module
The name of the module that has a bug.
website_hide_price

## Describe the bug
Adding a new block products on the website

When having no products published of a category it will give error 'null' the user will not notice that but when you want to edit the website page you will get that error. 
views/website_sale_template.xml line 60 is the error 

<attribute name="t-if">user_id.partner_id.website_show_price and not data['website_hide_price']</attribute>
needs to change to: 
<attribute name="t-if">user_id.partner_id.website_show_price and not data.get('website_hide_price')</attribute>

<template
        id="price_dynamic_filter_template_product_product_1"
        inherit_id="website_sale.price_dynamic_filter_template_product_product">
        <xpath expr="//span[hasclass('fw-bold')]" position="attributes">
                    <attribute name="t-if">
            user_id.partner_id.website_show_price and not data.get('website_hide_price')
                </attribute>
        </xpath>
</template>

**Comment by chienandalu** [comment]
Hi, @arnaud-tricore What's the version?

**Comment by arnaud-tricore** [comment]
Odoo v16.0
For the module itself I downloaded the latest version @chienandalu

**Comment by chienandalu** [comment]
Can you propose a PR?

**Comment by arnaud-tricore** [comment]
views/website_sale_template.xml line 60 is the error

user_id.partner_id.website_show_price and not data['website_hide_price']
needs to change to:
user_id.partner_id.website_show_price and not data.get('website_hide_price')

**Comment by arnaud-tricore** [comment]
Give me a moment @chienandalu
