### ISSUE TITLE
[16.0] website_sale_hide_price - Show price in comparison tool and wishlist

### ISSUE THREAD

**Issue by sergiuga** [OCA/e-commerce#855]
## Module
website_sale_hide_price

## Describe the bug
After restricting access to public user, the price is still available in wishlist and comparison tool and products can be added to cart.

## To Reproduce
Version affected - Odoo 16 CE
1. Restrict public user to see prices in shop - working on shop page and product page
2. Add products to wishlist and to comparison tool
3. Product prices and "Add to cart" button available and working

**Expected behavior**
No "Add to cart" and product price available to restricted products
**Additional context**
![website_hide_price_nohide](https://github.com/OCA/e-commerce/assets/28352258/d8e21236-f0c6-46dd-81f0-0fbfc3cdc80f)

**Comment by pedrobaeza** [comment]
Install https://github.com/OCA/e-commerce/tree/16.0/website_sale_comparison_hide_price for the first one and a new module `website_sale_wishlist_hide_price` is needed for the second.
