### ISSUE TITLE
Update website_sale_payment_term_acquirer to version 16/17

### ISSUE THREAD

**Issue by kubangab** [OCA/e-commerce#870]
**Is your feature request related to a problem?**
In Odoo website is very focused on B2C and not so much B2B. So when a customer selects Invoices (which is the standard payment terms for B2B, the order will not be confirmed until someone confirms the orders and move from Offer to Order in the backend.

**Describe the solution you'd like**
As I  can understand from the description this module does this exactly and look at the customer settings and if they have for example 30 days net the order will be created and a confirmation mail will be send to the customer. 

**Describe alternatives you've considered**
I haven't found any setting in Odoo to force an order on the website to be placed if they select Invoice. The standard behavior seems to be that the customer get mail where they need to pay first before the order is placed.

**Additional context**
The B2B part of the website is very week and here some of these modules like this one is actual very crucial.

**Comment by pedrobaeza** [comment]
Please follow the migration progress in the dedicated issues, or contact the authors for funding its migration.

**Comment by SirPyTech** [comment]
@kubangab if you are still interested in this, see https://github.com/OCA/e-commerce/pull/1197.
